### ISSUE TITLE
Improve the UI of contact form and add validation to the form

### ISSUE THREAD

**Issue by ankitbajpai65** [RIKI-05/MOMOMIA#160]
Hey @RIKI-05, I want to improve the UI of the website's contact form with an additive feature of its validation. So, therefore, please assign me this issue so that I can work on the same.
Thanks!
![image](https://user-images.githubusercontent.com/85179394/195435522-08d3d1a1-aac7-41be-8ccd-bea2bc2a0470.png)

**Comment by kituuu** [comment]
Hey Di, I updated the contact UI but I don't know how to validate the form...

**Comment by RIKI-05** [comment]
@ankitbajpai65 ...sorry but @kituuu have already made one....if you could make terms of service page attractive then please go ahead

**Comment by ankitbajpai65** [comment]
Okay. But at present, I am not getting any major improvement on the "terms of service" page. If you have any suggestions in your mind, please tell me so that I could do that.

**Comment by RIKI-05** [comment]
@ankitbajpai65 

- set the target of the terms of services page to black so that it can open in a different tab when I open the same


- Just add the navbar and in the navbar remove home categories and hygiene clickables and just leave the contact us clickable (make sure it's working)


Can you do that?

**Comment by ankitbajpai65** [comment]
Yes, I can do that. Assign this issue to me.
Thanks!
